joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

joint_position_example_controller:
    type: franka_example_controllers/JointPositionExampleController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    arm_id: panda

joint_position_example_controller_sim:
    type: franka_example_controllers/JointPositionExampleControllerSim
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    arm_id: panda


